---
output:
  html_document:
  keep_md: yes
self_contained: no
code_folding: hide
---
  
# Station similarities

```{r, echo = F, warning = F, message = F}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(tidyverse)
library(sf)
library(ggmap)
library(mapview)
library(lubridate)
library(readxl)
library(gridExtra)
library(vegan)
library(ggdendro)
library(dendextend)
library(mapview)

load(file = '../data/biodat.RData')
load(file = '../data/chmdat.RData')
load(file = '../data/simdat.RData')
```

```{r, fig.height = 6, fig.width = 4}
locs <- chmdat %>% 
  select(station, lon, lat) %>% 
  unique 

# get the extent
dat_ext <- make_bbox(locs$lon, locs$lat, f = 0.05)

# get the base map using the extent
bsmap <-  get_map(location = dat_ext, maptype = 'toner-lite', source = 'stamen', zoom = 9)

# plot the basemap
ggmap(bsmap) + 
  geom_point(data = locs, aes(x = lon, y = lat), colour = 'tomato1', size = 8) +
  geom_text(data = locs, aes(x = lon, y = lat, label = station)) + 
  theme_bw(base_family = 'serif') +
  theme(axis.title = element_blank())
```

## Monthly averages by water chemistry {.tabset}

```{r}
toplo <- read_excel('../raw/WOAC_data_5-1-2018_for_Nina.xlsx', sheet = 'ALL_DATA', na = c('', '-999')) %>% 
  select(Date_collected, STATION_NO, LATITUDE_DEC, LONGITUDE_DEC, NISKIN_NO, CTDTMP_DEG_C_ITS90, 
         CTDSAL_PSS78, `Omega Ar`) %>% 
  rename(
    date = Date_collected, 
    station = STATION_NO,
    lat = LATITUDE_DEC,
    lon = LONGITUDE_DEC,
    niskin = NISKIN_NO,
    temp = CTDTMP_DEG_C_ITS90,
    sal = CTDSAL_PSS78,
    ara = `Omega Ar`
  ) %>% 
  mutate(
    date = as.Date(date)
  ) %>% 
  gather('var', 'val', temp:ara) %>% 
  group_by(station) %>% 
  mutate(
    lat = mean(lat), 
    lon = mean(lon),
    yr = year(date), 
    mo = month(date)
  ) %>% 
  filter(mo %in% c(4, 7, 9, 10)) %>%
  mutate(
    mo = case_when(
      yr == 2014 & mo == 10 ~ 9,
      TRUE ~ mo
    ),
    mo = month(mo, label = T)
  )

# ggplot(toplo, aes(x = factor(station), y = val, fill = factor(yr))) + 
#   geom_boxplot(position = 'dodge') +
#   facet_grid(var ~ mo, scales = 'free_y')

# average across years by month
toplo2 <- toplo %>% 
  group_by(station, var, mo, lat, lon) %>% 
  summarise(
    valmn = mean(val, na.rm = T),
    valsd = sd(val, na.rm = T)
  )

pbase <- theme_bw(base_size = 14, base_family = 'serif') + 
  theme(
    axis.title = element_blank(), 
    strip.background = element_blank() 
  ) 
```

### Salinity

```{r, fig.height = 6, fig.width = 8}
salplo <- toplo2 %>% 
  filter(var %in% 'sal')
p1 <- ggmap(bsmap) +
  geom_point(data = salplo, aes(x = lon, y = lat, size = valmn, alpha = valsd), colour = 'tomato1') + 
  geom_point(data = salplo, aes(x = lon, y = lat, size = valmn), pch = 21) + 
  scale_size('Salinity (ave)', range = c(1, 10)) +
  scale_alpha('Salinity (sd)') +
  coord_map() + 
  facet_wrap(~mo) + 
  pbase +
  guides(alpha = guide_legend(override.aes = list(size=3)))

p1
```

### Temperature

```{r, fig.height = 6, fig.width = 8}
tempplo <- toplo2 %>% 
  filter(var %in% 'temp')
p2 <- ggmap(bsmap) +
  geom_point(data = tempplo, aes(x = lon, y = lat, size = valmn, alpha = valsd), colour = 'tomato1') + 
  geom_point(data = tempplo, aes(x = lon, y = lat, size = valmn), pch = 21) + 
  scale_size('Temp (ave)', range = c(1, 10)) +
  scale_alpha('Temp (sd)') +
  coord_map() + 
  facet_wrap(~mo) + 
  pbase +
  guides(alpha = guide_legend(override.aes = list(size=3)))

p2
```

### Omega

```{r, fig.height = 6, fig.width = 8}
araplo <- toplo2 %>% 
  filter(var %in% 'ara')
p3 <- ggmap(bsmap) +
  geom_point(data = araplo, aes(x = lon, y = lat, size = valmn, alpha = valsd), colour = 'tomato1') + 
  geom_point(data = araplo, aes(x = lon, y = lat, size = valmn), pch = 21) + 
  scale_size('Omega (ave)', range = c(1, 10)) +
  scale_alpha('Omega (sd)') +
  coord_map() + 
  facet_wrap(~mo) + 
  pbase +
  guides(alpha = guide_legend(override.aes = list(size=3)))

p3
```

## Clustering {.tabset}

```{r}
toclst <- toplo2 %>%
  ungroup %>% 
  filter(mo %in% 'Sep') %>% 
  select(station, var, valmn) %>% 
  spread(var, valmn) %>% 
  data.frame %>% 
  column_to_rownames('station')

# dissimilarity
dis <- toclst %>% 
  vegdist(method = 'euclidean')

# clsuters
clst <- dis %>% 
  hclust(method = 'average')
```

### Dendrogram

```{r}
clstcut <- 3

# get cut groups
clstgrps <- cutree(clst, k = 3)

# get order
clstord <- order.hclust(clst) %>%
  clstgrps[.] %>%
  unique

# get colors, correct by order
cols <- mapviewGetOption("vector.palette")(as.numeric(clstcut)) %>%
  .[clstord]

p1 <- clst %>% 
  as.dendrogram %>% 
  set("branches_k_color", k = clstcut, value = cols) %>%
  set("labels_colors", k = clstcut, value = cols) %>%
  set("labels_cex", 0.8) 
plot(p1)
```

### Station dissimilarities

```{r, fig.height = 7, fig.width = 6}
# prep distance data to plot
# long format of dist matrix
toplo <- dis %>% 
  as.matrix %>% 
  as.data.frame %>%
  rownames_to_column('station') %>% 
  gather('station2', 'dist', -station) %>% 
  arrange(dist) %>% 
  mutate(
    dist = ifelse(station == station2, NA, dist)
    )

# get site order levels based on clustering
sitfc <- clst$labels[clst$order]
toplo <- toplo %>% 
  mutate(
    station = factor(station, levels = sitfc), 
    station2 = factor(station2, levels = sitfc)
  )
  
# plot
p <- ggplot(toplo) + 
  geom_tile(aes(x = station, y = station2, fill = dist), colour = 'black') +
  scale_x_discrete('', expand = c(0, 0)) + 
  scale_y_discrete('', expand = c(0, 0)) +
  scale_fill_gradient2('Dissimilarity between stations\nby water chemistry', low = 'lightblue', mid = 'white', high = 'tomato1', midpoint = 2) +
  guides(fill = guide_colourbar(barheight = 0.5, barwidth = 10, label.theme = element_text(size = 11, angle = 0))) + 
  pbase

# index values of cluster cuts
brks <- clstgrps %>% 
  .[clst$order] %>% 
  duplicated %>% 
  `!` %>% 
  which %>% 
  `-` (0.5) %>% 
  .[-1]

p <- p + 
  geom_vline(xintercept = brks, size = 1.5) +
  geom_hline(yintercept = brks, size = 1.5) +
  theme_bw(base_family = 'serif') +
  theme(
    legend.position = 'top',
    legend.direction = 'horizontal'
  ) 


return(p)
```

### Map

```{r, fig.height = 6, fig.width = 4}
mapplo <- locs %>% 
  mutate(clstgrps = clstgrps)

# plot the basemap
ggmap(bsmap) + 
  geom_point(data = mapplo, aes(x = lon, y = lat, fill = clstgrps), pch = 21, size = 8, alpha = 0.7) +
  geom_text(data = mapplo, aes(x = lon, y = lat, label = station)) + 
  scale_fill_viridis_c() + 
  theme_bw(base_family = 'serif') +
  theme(
    axis.title = element_blank(), 
    legend.position = 'none'
    )
```

```{r eval = F}
simdatts <- simdat %>%
  group_by(station) %>% 
  nest %>% 
  mutate(
    datts = map(data, function(x){
      
      ts(x$ara, start = 2008, frequency = nrow(x))
      
    })
  )
  spread(station, ara)
```

